version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  strapi:
    image: vk2615/strapi:latest  # <- prebuilt image
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: "production"
      DATABASE_CLIENT: "postgres"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "strapi"
      DATABASE_USERNAME: "strapi"
      DATABASE_PASSWORD: "strapi_password"

      APP_KEYS: "9f8070cf3b8a900cb61042d1e51a84fb5e3fc1c02c14b33bcc66a2405a064bc8,secondKeyHere"
      ADMIN_JWT_SECRET: "0f67c7480e46be7933c9aaaf7794564b1c4867f377c15fd75aaaf7832bf0469e"
      API_TOKEN_SALT: "wVDIKA5IV8bKcn9ttl/Wsg=="
      TRANSFER_TOKEN_SALT: "UXVyWLpQOqSw9aLNVe6uhA=="
      JWT_SECRET: "++L1GiTBO08qvp+bnCdXpw=="
      FLAG_NPS: "true"
      FLAG_PROMOTE_EE: "false"
    depends_on:
      - postgres
    command: "npm run start"

volumes:
  postgres_data:
