apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strapi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vkig2615/strapi-app.git
    path: strapi
    targetRevision: main
    helm:
      values: |
        image:
          repository: strapi/strapi
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
