name: Deploy Strapi to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install ArgoCD CLI  ||
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 ||
          chmod +x /usr/local/bin/argocd ||

      - name: Sync Strapi Deployment
        run: |
          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure
          argocd app sync strapi-app
          argocd app wait strapi-app
        env:
          ARGOCD_SERVER: localhost:8080
          ARGOCD_PASSWORD: dDRU33doqxn7lP5S
OS
